### PR TITLE
Update fonts

### PR DESCRIPTION
**Pull request by ray1984**
Update google fonts for new symbols (ex. russian rouble sign)

### CODE REVIEW

**Comment by johnkil** [comment]
@ray1984 It is also necessary to update the condensed fonts.

**Comment by johnkil** [comment]
@ray1984  Will you do?

**Comment by ray1984** [comment]
When will this changes appear in gradle?

**Comment by johnkil** [comment]
20 minutes.

**Comment by johnkil** [comment]
ready :yum:
```groovy
compile 'com.github.johnkil.android-robototextview:robototextview:2.4.2'
```

**Comment by ray1984** [comment]
@johnkil Tnx

**Pull request closed without merging**
